version: "3.9"
services:
  flask:
    build: 
      context: .
      dockerfile: Dockerfile
    image: mahinraza556/flask-app:crud-with-mongodb
    ports:
      - "5000:5000"
    environment: # Load variable value from .env file
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
    #env_file:
    # - .env
    networks:
      - my_network
    depends_on:
      mongodb:
        condition: service_healthy

  mongodb:
    image: mongo:4.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    volumes:
      - db_data:/data/db
    networks:
      - my_network
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  my_network:
    driver: bridge

volumes:
  db_data: