version: "3.9"
services:
  flask:
    build: 
      context: .
      dockerfile: Dockerfile
    image: mahinraza556/flask-app:crud-with-redis
    ports:
      - "5000:5000"
    environment: # Load variable value from .env file
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_DB: ${REDIS_DB}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    #env_file:
    # - .env
    networks:
      - my_network
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis:6.0
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    networks:
      - my_network
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  my_network:
    driver: bridge

volumes:
  redis_data: